# Use the official Jupyter Docker image as the base image
FROM jupyter/base-notebook:latest

# Set the command to run Jupyter Notebook when the container launches
CMD ["jupyter", "notebook", "--ip='0.0.0.0'", "--port=8888", "--no-browser", "--allow-root"]
